name: flutter_context_menu
description: Create and display a customizable context menus in your app.
version: 0.1.0
homepage: https://github.com/salah-rashad/flutter_context_menu
repository: https://github.com/salah-rashad/flutter_context_menu

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0